name: Il mio primo github action
on: 
  push: 
jobs: 
  italian-job:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4  
      - run: ls
      - run: pwd
      - run: ls -la  
      - run: java -version 
      - run: cd template-progetto 
      - run: ls
      - run: pwd 
        working-directory: template-progetto
      - run: mvn install
        working-directory: template-progetto
      - run: java -jar /home/runner/.m2/repository/com/mycompany/app/my-app/1.0-SNAPSHOT/my-app-1.0-SNAPSHOT.jar
      
